name: Deploy Dokkie to GH Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Dokkie
        run: npx dokkie --url=https://silvandiepen.github.io/dokkie
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dokkie
          publish_branch: gh-pages  # deploying branch
